export const dynamic = 'force-dynamic';

import { NextRequest } from 'next/server';
import { withPermission } from '@/lib/api/withAuth';
import { errorResponse, successResponse } from '@/lib/api/response';
import { createSupabaseServerClient } from '@/lib/supabase/server';
import { generateGroqCompletion } from '@/lib/ai/groq.client';
import { sendWhatsApp } from '@/features/africas-talking';
import { z } from 'zod';

const sendParentSchema = z.object({
  channel: z.enum(['sms', 'whatsapp']).default('whatsapp'),
});

export const POST = withPermission('reports', 'create', async (request: NextRequest, { user, params }: { user: any; params: { id: string } }) => {
  const supabase = await createSupabaseServerClient();
  const schoolId = user.schoolId!;

  const body = await request.json().catch(() => ({}));
  const parsed = sendParentSchema.safeParse(body);
  const channel = parsed.success ? parsed.data.channel : 'whatsapp';

  const { data: report } = await supabase
    .from('report_cards')
    .select(`
      *,
      students!inner(student_id, first_name, last_name, admission_number),
      terms!inner(name, academic_year)
    `)
    .eq('report_id', params.id)
    .eq('school_id', schoolId)
    .single();

  if (!report) {
    return errorResponse('Report card not found', 404);
  }

  const { data: guardians } = await supabase
    .from('student_guardians')
    .select('guardian_user_id, relationship')
    .eq('student_id', (report.students as any).student_id);

  if (!guardians || guardians.length === 0) {
    return errorResponse('No guardians found for this student', 404);
  }

  const guardianUserIds = guardians.map((g) => g.guardian_user_id);
  const { data: guardianUsers } = await supabase
    .from('users')
    .select('user_id, first_name, last_name, phone')
    .in('user_id', guardianUserIds);

  if (!guardianUsers || guardianUsers.length === 0) {
    return errorResponse('No guardian contact info found', 404);
  }

  const studentName = `${(report.students as any).first_name} ${(report.students as any).last_name}`;
  const termName = (report.terms as any).name;
  const academicYear = (report.terms as any).academic_year;
  const reportUrl = `${request.nextUrl.origin}/reports/${params.id}`;

  let parentSummary = '';
  try {
    const ai = await generateGroqCompletion({
      system: 'You are a school communication assistant. Write a warm, parent-friendly 2-3 sentence summary of a student\'s report card. Avoid educational jargon. Focus on encouraging parent-teacher partnership.',
      prompt: `Write a brief parent-friendly summary for ${studentName}'s report card.
Term: ${termName} ${academicYear}
Overall average: ${report.overall_average ?? 'N/A'}%
Overall level: ${report.overall_level ?? 'N/A'}
Generated by AI from assessment data.`,
      responseFormat: 'text',
      temperature: 0.3,
      requestLabel: `report.parent-summary.${params.id}`,
      cache: { schoolId },
    });
    parentSummary = ai.data;
  } catch {
    parentSummary = `${studentName}'s report for ${termName} ${academicYear} is now available with an overall average of ${report.overall_average ?? 'N/A'}%.`;
  }

  const results: any[] = [];
  for (const guardian of guardianUsers) {
    if (!guardian.phone) {continue;}
    const message = `Dear ${guardian.first_name}, ${parentSummary}\n\nView full report: ${reportUrl}\n\n- ${report.school_name ?? 'School'}`;

    try {
      if (channel === 'whatsapp') {
        const sent = await sendWhatsApp({ to: [guardian.phone], message });
        results.push({ guardianId: guardian.user_id, channel: 'whatsapp', sentOk: sent.success, providerResponse: sent });
      } else {
        const { sendSms } = await import('@/features/africas-talking');
        const sent = await sendSms({ to: [guardian.phone], message });
        results.push({ guardianId: guardian.user_id, channel: 'sms', sentOk: sent.success, providerResponse: sent });
      }
    } catch (err) {
      results.push({ guardianId: guardian.user_id, channel, sentOk: false, error: err instanceof Error ? err.message : 'Send failed' });
    }
  }

  const delivered = results.filter((r) => r.sentOk).length;
  const failed = results.filter((r) => !r.sentOk).length;

  await supabase.from('notifications').insert({
    school_id: schoolId,
    user_id: user.id,
    title: 'Report sent to parents',
    body: `${studentName}'s report sent to ${delivered} parent(s) via ${channel}${failed > 0 ? ` (${failed} failed)` : ''}`,
    type: 'info',
  });

  return successResponse({
    studentName,
    channel,
    totalGuardians: guardianUsers.length,
    delivered,
    failed,
    details: results,
  });
});
